[package]
name = "rust-cookbook"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

build = "build.rs"

[dependencies]
rand = "0.3.15"
byteorder = "1.0.0"
error-chain = "0.8.0"
json = "0.11.5"
toml = "0.3"
serde_derive = "0.9.9"


[build-dependencies]
skeptic = "0.7.1"

[dev-dependencies]
skeptic = "0.7.1"
