[package]
name = "rust-cookbook"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

build = "build.rs"

[dependencies]
rand = "0.3.15"
byteorder = "1.0.0"
error-chain = "0.8.0"
toml = "0.4"
petgraph = "0.4.3"
crossbeam = "0.2"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
rayon = "0.6.0"
clap = "2.22.2"

[build-dependencies]
skeptic = "0.7.1"

[dev-dependencies]
skeptic = "0.7.1"
