[package]
name = "rust-cookbook"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

build = "build.rs"

[dependencies]
byteorder = "1.0.0"
error-chain = "0.8.0"
json = "0.11.5"

[build-dependencies]
skeptic = "0.6"

[dev-dependencies]
skeptic = "0.6"
