[package]
name = "rust-cookbook"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

build = "build.rs"

[dependencies]
byteorder = "1.0"
clap = "2.0"
crossbeam = "0.2"
error-chain = "0.10"
petgraph = "0.4"
rand = "0.3"
rayon = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.4"
url = "1.4"
reqwest = "0.6"
env_logger = "0.4"
syslog = "3.2.0"

[build-dependencies]
skeptic = "0.9"

[dev-dependencies]
skeptic = "0.9"
