[package]
name = "rust-cookbook"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

build = "build.rs"

[dependencies]
rand = "0.3"
byteorder = "1.0"
error-chain = "0.10"
toml = "0.4"
petgraph = "0.4"
crossbeam = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rayon = "0.7"
clap = "2.0"
url = "1.4.0"

[build-dependencies]
skeptic = "0.9"

[dev-dependencies]
skeptic = "0.9"
